name: project5
on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        cd application
      docker pull kkoppin001/docker-repo-koppin:v1
        docker build -t docker-repo-koppin:v1 .
        docker tag docker-repo-koppin:v1 kkoppin001/v1
        docker push kkoppin001/v1
